<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CmsFaqSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        //$this->db->table('cms_faqs')->truncate();

        $data = [
            [
                'category_id' => 1,
                'question'    => 'How do I book a tour package online?',
                'answer'      => 'Select your preferred destination, travel dates, and number of travelers, then follow the checkout steps on the website.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 1,
                'question'    => 'Can I reserve a package for a future travel date?',
                'answer'      => 'Yes, you can choose any available travel date during booking; if your preferred date is unavailable, contact support for alternatives.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 1,
                'question'    => 'Is group booking available for family travel?',
                'answer'      => 'Most packages support group booking; you can select the traveler count or request a customized group itinerary through our support team.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 2,
                'question'    => 'What payment methods do you accept?',
                'answer'      => 'We accept credit/debit cards, net banking, UPI, and selected digital wallets. International payments are processed through secure payment gateways.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 2,
                'question'    => 'Do package prices include taxes and fees?',
                'answer'      => 'Package prices shown include all standard taxes. Any additional optional services or customizations may incur extra fees.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 2,
                'question'    => 'Can I pay in installments for a tour booking?',
                'answer'      => 'Installment payments may be available depending on the package and payment provider. Check the payment page or contact customer service for installment options.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 3,
                'question'    => 'What documents do I need to carry for domestic travel?',
                'answer'      => 'Carry a valid government-issued photo ID such as an Aadhar card, passport, or driver’s license, along with your booking confirmation.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 3,
                'question'    => 'Do I need a passport for international tours?',
                'answer'      => 'Yes, a valid passport is required for all international travel, and some destinations also require visas obtained before departure.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 3,
                'question'    => 'How can I get a visa for my destination?',
                'answer'      => 'Visa requirements vary by country. Refer to the travel advice on our destination page or consult the local embassy for current visa procedures.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 4,
                'question'    => 'What type of accommodation is provided in the package?',
                'answer'      => 'Accommodation details are listed in each package. Most packages include 3-star or 4-star hotel stays; luxury upgrades are available on request.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 4,
                'question'    => 'Can I request a single room instead of a double room?',
                'answer'      => 'Single room requests can be accommodated, though they may incur an additional single-room surcharge depending on the hotel policy.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 4,
                'question'    => 'Are meals included with the accommodation?',
                'answer'      => 'Many of our packages include breakfast or half-board options. Check the package details for the exact meal plan included.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 5,
                'question'    => 'Do packages include airport transfers?',
                'answer'      => 'Airport transfers are included in selected packages and are specified in the itinerary. If not included, transfers can be arranged for an additional fee.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 5,
                'question'    => 'What transportation is used during the trip?',
                'answer'      => 'Transportation details are provided in each package and may include coach buses, private cars, or domestic flights as required by the itinerary.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 5,
                'question'    => 'Can I add extra sightseeing stops along the route?',
                'answer'      => 'Yes, extra sightseeing stops can be requested subject to itinerary feasibility and may involve extra charges.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 6,
                'question'    => 'What is your cancellation policy?',
                'answer'      => 'Cancellation policies vary by package. Refer to the package terms for the exact refund schedule and conditions.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 6,
                'question'    => 'Can I change my travel date after booking?',
                'answer'      => 'Date changes are possible depending on availability and may incur change fees. Contact support as soon as your plans change.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 6,
                'question'    => 'How long does it take to receive a refund?',
                'answer'      => 'Refund processing usually takes 7–14 business days after approval, depending on your bank or payment provider.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 7,
                'question'    => 'Will I get a local guide during the tour?',
                'answer'      => 'Many packages include a local guide for city tours and cultural experiences, as noted in the package itinerary.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 7,
                'question'    => 'Are there recommended cultural etiquettes to follow?',
                'answer'      => 'Yes. We provide destination-specific etiquette tips, including dress codes and respectful behavior for cultural sites.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 7,
                'question'    => 'Can I book local experiences like cooking classes or village visits?',
                'answer'      => 'Yes, we offer optional local experiences that can be added to your itinerary at the time of booking or by contacting customer service.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 8,
                'question'    => 'What health precautions should I take before traveling?',
                'answer'      => 'Check destination-specific health advisories, stay hydrated, and carry any personal medications and travel health insurance documents.',
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 8,
                'question'    => 'Is travel insurance included in the package?',
                'answer'      => 'Travel insurance is not included by default in most packages, but we can help arrange a policy for an additional fee.',
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 8,
                'question'    => 'What happens if there is a travel advisory during my trip?',
                'answer'      => 'If a travel advisory affects your itinerary, our team will contact you with the safest alternative arrangements or rescheduling options.',
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 1,
                'question'    => 'Can I book a package for one-way travel only?',
                'answer'      => 'Some packages allow one-way arrivals with optional departure extensions. Confirm availability when booking.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 2,
                'question'    => 'Do you offer promotional discounts during off-season travel?',
                'answer'      => 'Yes, seasonal promotions and early bird discounts are often available. Check the website for current offers.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 3,
                'question'    => 'Can I travel with a minor without a parent?',
                'answer'      => 'Minors traveling alone may require additional consent forms and documentation. Review government guidelines before booking.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 4,
                'question'    => 'Are hotels selected close to major attractions?',
                'answer'      => 'We aim to book hotels in convenient locations near popular attractions whenever possible.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 5,
                'question'    => 'Will I have a dedicated driver for private transfers?',
                'answer'      => 'Private transfer packages include a dedicated driver. Shared transfers may use standard coach services.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 7,
                'question'    => 'Do you arrange custom cultural itineraries for festival travel?',
                'answer'      => 'Yes, we can build custom itineraries around local festivals and events with authentic experiences included.',
                'sort_order'  => 5,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'category_id' => 8,
                'question'    => 'Do I need vaccinations for certain destinations?',
                'answer'      => 'Some destinations may require vaccinations; check health advisory notices and consult your doctor before travel.',
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        $this->db->table('cms_faqs')->insertBatch($data);
    }
}
