<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CmsTestimonialsSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'name'        => 'Aarav Mehta',
                'designation' => 'Senior Marketing Manager',
                'company'     => 'Blue Horizon Travel',
                'location'    => 'Mumbai, India',
                'message'     => 'Our honeymoon in the Maldives was perfectly arranged, from the private transfer to the sunset cruise. Every detail felt thoughtful, and the experience exceeded our expectations.',
                'rating'      => 5,
                'featured'    => 1,
                'sort_order'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Sofia Fernandes',
                'designation' => 'Operations Lead',
                'company'     => 'Fernandez Family Travels',
                'location'    => 'Goa, India',
                'message'     => 'We booked a family vacation to Dubai and everything was smooth. The itinerary was well paced, the guides were friendly, and the hotels were excellent.',
                'rating'      => 5,
                'featured'    => 1,
                'sort_order'  => 2,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Nishant Kapoor',
                'designation' => 'Travel Consultant',
                'company'     => 'Skyline Tours',
                'location'    => 'Delhi, India',
                'message'     => 'The Europe package was beautifully curated. We loved the city guides, comfortable transfers, and the balance between sightseeing and free time.',
                'rating'      => 5,
                'featured'    => 1,
                'sort_order'  => 3,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Priya Nair',
                'designation' => 'HR Executive',
                'company'     => 'Nair & Co.',
                'location'    => 'Kochi, India',
                'message'     => 'Our Kerala retreat was stress-free from start to finish. The local experiences made the trip memorable, and the support team was quick to respond.',
                'rating'      => 5,
                'featured'    => 1,
                'sort_order'  => 4,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Rohan Bansal',
                'designation' => 'Product Manager',
                'company'     => 'Bansal Ventures',
                'location'    => 'Bengaluru, India',
                'message'     => 'The Bali itinerary was detailed and flexible. We especially appreciated the local transport coordination and the helpful travel notes provided.',
                'rating'      => 4,
                'featured'    => 0,
                'sort_order'  => 5,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Anita Shah',
                'designation' => 'Teacher',
                'company'     => 'Shah Education Trust',
                'location'    => 'Ahmedabad, India',
                'message'     => 'The family holiday to Thailand was easy to manage thanks to the clear itinerary and friendly support team. The kids loved the beach activities.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 6,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Vinay Menon',
                'designation' => 'Freelance Photographer',
                'company'     => 'Frame & Light Studio',
                'location'    => 'Chennai, India',
                'message'     => 'We chose a luxury Dubai package and the experience was seamless. The guides were knowledgeable and the hotel selection was excellent.',
                'rating'      => 4,
                'featured'    => 0,
                'sort_order'  => 7,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Meera Iyer',
                'designation' => 'Business Owner',
                'company'     => 'Iyer Boutique',
                'location'    => 'Pune, India',
                'message'     => 'Our Greece trip was beautifully organized, with each transfer and sightseeing stop clearly communicated. The itinerary felt premium without being rushed.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 8,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Karan Desai',
                'designation' => 'Software Engineer',
                'company'     => 'Northstar Labs',
                'location'    => 'Hyderabad, India',
                'message'     => 'The Maldives escape was romantic and well planned. We would definitely book again for a short, relaxing getaway.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 9,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Neha Chawla',
                'designation' => 'Real Estate Advisor',
                'company'     => 'Chawla Realty',
                'location'    => 'Jaipur, India',
                'message'     => 'The cultural tour through Europe was immersive and comfortable. The local guides added so much depth to every stop.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 10,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Dhruv Saini',
                'designation' => 'Sales Director',
                'company'     => 'Summit Global',
                'location'    => 'Noida, India',
                'message'     => 'The custom itinerary for our honeymoon was brilliantly executed. We loved the hidden gems and the private transfers arranged for us.',
                'rating'      => 5,
                'featured'    => 1,
                'sort_order'  => 11,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Sakshi Verma',
                'designation' => 'Product Designer',
                'company'     => 'Verma Studio',
                'location'    => 'Lucknow, India',
                'message'     => 'The entire family trip to Singapore was very well coordinated. Meals, transport, and sightseeing were all arranged with great care.',
                'rating'      => 4,
                'featured'    => 0,
                'sort_order'  => 12,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Aditya Rao',
                'designation' => 'Consultant',
                'company'     => 'Bluebird Solutions',
                'location'    => 'Bengaluru, India',
                'message'     => 'We planned a short Dubai getaway and were impressed by the choices in hotels and local experiences. The support team was very responsive.',
                'rating'      => 4,
                'featured'    => 0,
                'sort_order'  => 13,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Kavya Menon',
                'designation' => 'Event Planner',
                'company'     => 'Bloom Event House',
                'location'    => 'Coimbatore, India',
                'message'     => 'Our island vacation in the Maldives felt luxurious and relaxed. The package covered everything we needed, and the service was very polished.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 14,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'name'        => 'Harsh Vora',
                'designation' => 'Entrepreneur',
                'company'     => 'Vora Ventures',
                'location'    => 'Surat, India',
                'message'     => 'The European package struck a perfect balance between comfort and discovery. We enjoyed every transfer and would happily recommend it to friends.',
                'rating'      => 5,
                'featured'    => 0,
                'sort_order'  => 15,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        $this->db->table('cms_testimonials')->insertBatch($data);
    }
}
